### ISSUE TITLE
Running without normal bam

### ISSUE THREAD

**Issue by cytham** [czc/nb_distribution#2]
Hi is it possible to run novoBreak with just the tumor bam and without the normal bam? if yes, how do i do it?

Thanks

**Comment by czc** [comment]
Hi,

Yes, you can make a mocked normal bam file by simulation to meet the interfaces of novoBreak pipeline. No requirement for the read depth or mutation types even error rate since you don't need any information from this mocked file.

But keep in mind, we cannot tell somatic or germline. If you only want somatic ones, you may need filter out germline ones by visiting some public resources such as 1000 Genome SV call set.

Hope this helps!

Thanks,
Zechen

**Comment by cytham** [comment]
Thanks for your reply.

I have simulated a bam file with one depth coverage of paired end reads and used it as the normal.bam. However, after finished running novobreak, I still did not get the output.vcf file, only the .kmer, germline and somatic read bam files.

Do I need to run any additional filter script to generate the vcf file?

Thanks

**Comment by czc** [comment]
It seems that it wasn't finished. These are not final outputs. You should see some directories and a final VCF file. You may need to allocate more time and memory for the one-sample case since we cannot filter out anything from the mocked normal bam. 

Thanks,
Zechen

**Comment by cytham** [comment]
I have more than 300GB free memory and more than 50 free threads for this run, is that enough? How do I explicitly allocate more time and memory for the run?

My tumor .bam was created by bwa whereas my mock.bam was by bowtie2. Will the different mappers affect the output?

This is the log for the run:
[Sat Sep  9 14:38:38 2017]
Building reference kmer...
Calculating number of paired reads ...
[fillin_bitvec] processed 1090115735 reads
There are 2423397003 reference kmers and 4362650584 non-reference kmers
Finished reference kmer building
[Sat Sep  9 17:11:12 2017]
Freed reference hash and begin building reads hash table...
[Sat Sep  9 17:11:12 2017]
[build_readshash] processed 1090115735 reads
[Sat Sep  9 18:30:37 2017]
 50074728 kmers loaded

[Sat Sep  9 18:30:39 2017]
Calculating kmers from control...
[cal_ctrl_kmers] processed   30999224 reads
[Sat Sep  9 18:39:12 2017]
Loading sequences...
[Sat Sep  9 19:30:20 2017]60288 reads
Remove duplicate sequences...
[Sat Sep  9 20:33:21 2017]60288 reads

48071331 kmers passed the minimum frequency cutoff in tumor (3) and maximum frequency cutoff in normal (3)
Program exit normally

Is the log normal?

Thanks,
Tham

**Comment by czc** [comment]
The memory and CPU cores are enough. If you don't run the job on a server which requests setting time and memory, then it would be OK. 

The mocked bam generated using Bowtie2 should be OK.

The log only shows the core novoBreak program's log information. This seems right. Besides, you should see logs from other part of the workflow and directories "group_reads" and "ssake". 

You can comment the line 26 and try the command of "run_novoBreak.sh" again. 

Thanks,
Zechen

**Comment by cytham** [comment]
I realized my mistake, I was using 'novoBreak' instead of 'run_novoBreak.sh'. 
It should run the other workflows now.
Thanks for your responses and help.

Tham
