### ISSUE TITLE
Inclusion in Bioconda

### ISSUE THREAD

**Issue by johanneskoester** [czc/nb_distribution#3]
Dear authors,
I would like to provide novobreak via [bioconda](https://bioconda.github.io). Is there a source code repository that could be used to build the tool? Pre-compiled binaries are problematic because we cannot guarantee minimal OS requirements in this case. Also, we would refer to other packages for bwa and samtools. Are there any version requirements for these two?

**Comment by czc** [comment]
Hi Johannes,

Just heard of bioconda. Really a cool project. The novoBreak core program can be found at https://github.com/czc/novobreak_src. The version of bwa is v0.7.10-r806-dirty. The samtools version is v1.3.  But I expect newer versions of bwa and samtools should be Okay though I have not tested. Please feel free to let me know if you have further questions.

Thanks,
Zechen

**Comment by johanneskoester** [comment]
xref: bioconda/bioconda-recipes#7106

**Comment by johanneskoester** [comment]
Thanks for your help. The inclusion is being worked on now.
