### ISSUE TITLE
infer_bp_v4.pl line 13 error

### ISSUE THREAD

**Issue by d-kk** [czc/nb_distribution#4]
Hi,

Tried to run the tool using the run_novoBreak.sh script and got the following error at the end of the log file, any ideas?:

1433560 kmers passed the minimum frequency cutoff in tumor (3) and maximum frequency cutoff in normal (3)
Program exit normally
[M::bam2fq_mainloop] processed 1007748 reads
begin kmer2id ...
kmer2id takes 2 seconds
begin id2pair...
id2pair takes 151 seconds
begin sorting ids...
sorting ids takes 5 seconds
begin output results...
Outputting results takes 2 seconds
Finished
0.txt
10.txt
11.txt
12.txt
13.txt
14.txt
15.txt
1.txt
2.txt
3.txt
4.txt
5.txt
6.txt
7.txt
8.txt
9.txt
[E::bwa_idx_load] fail to locate the index files
x??
No such file or directory at /mnt/local_tools/nb_distribution/infer_bp_v4.pl line 13.

**Comment by czc** [comment]
It's not the error of infer_bp_v4.pl. You should index your reference using bwa. Also, make sure the novoBreak directory is in your PATH. Thanks!

-Zechen

**Comment by d-kk** [comment]
OK,

here is the path:

echo $PATH
/mnt/data_45_samples/novoBreak_test/nb_distribution/:/mnt/galaxy/tools/bin:/usr/lib/postgresql/9.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin

Indexed the reference with the version of bwa in nb_distribution/ and re ran the script here is the tailof the log file:

1433560 kmers passed the minimum frequency cutoff in tumor (3) and maximum frequency cutoff in normal (3)
Program exit normally
[M::bam2fq_mainloop] processed 1007748 reads
begin kmer2id ...
kmer2id takes 1 seconds
begin id2pair...
id2pair takes 146 seconds
begin sorting ids...
sorting ids takes 5 seconds
begin output results...
Outputting results takes 2 seconds
Finished
0.txt
10.txt
11.txt
12.txt
13.txt
14.txt
15.txt
1.txt
2.txt
3.txt
4.txt
5.txt
6.txt
7.txt
8.txt
9.txt
Can't exec "SSAKE": No such file or directory at /mnt/local_tools/nb_distribution/run_ssake.pl line 34.
Can't exec "SSAKE": No such file or directory at /mnt/local_tools/nb_distribution/run_ssake.pl line 34.
No such file or directory at /mnt/local_tools/nb_distribution/run_ssake.pl line 39.
No such file or directory at /mnt/local_tools/nb_distribution/run_ssake.pl line 39.
No such file or directory at /mnt/local_tools/nb_distribution/run_ssake.pl line 39.
Can't exec "SSAKE": No such file or directory at /mnt/local_tools/nb_distribution/run_ssake.pl line 34.
No such file or directory at /mnt/local_tools/nb_distribution/run_ssake.pl line 39.
Can't exec "SSAKE": No such file or directory at /mnt/local_tools/nb_distribution/run_ssake.pl line 34.
No such file or directory at /mnt/local_tools/nb_distribution/run_ssake.pl line 39.
Can't exec "SSAKE": No such file or directory at /mnt/local_tools/nb_distribution/run_ssake.pl line 34.
No such file or directory at /mnt/local_tools/nb_distribution/run_ssake.pl line 39.
Can't exec "SSAKE": No such file or directory at /mnt/local_tools/nb_distribution/run_ssake.pl line 34.
No such file or directory at /mnt/local_tools/nb_distribution/run_ssake.pl line 39.
No such file or directory at /mnt/local_tools/nb_distribution/run_ssake.pl line 39.
Can't exec "SSAKE": No such file or directory at /mnt/local_tools/nb_distribution/run_ssake.pl line 34.
Can't exec "SSAKE": No such file or directory at /mnt/local_tools/nb_distribution/run_ssake.pl line 34.
No such file or directory at /mnt/local_tools/nb_distribution/run_ssake.pl line 39.
No such file or directory at /mnt/local_tools/nb_distribution/run_ssake.pl line 39.
Can't exec "SSAKE": No such file or directory at /mnt/local_tools/nb_distribution/run_ssake.pl line 34.
No such file or directory at /mnt/local_tools/nb_distribution/run_ssake.pl line 39.
Can't exec "SSAKE": No such file or directory at /mnt/local_tools/nb_distribution/run_ssake.pl line 34.
No such file or directory at /mnt/local_tools/nb_distribution/run_ssake.pl line 39.
Can't exec "SSAKE": No such file or directory at /mnt/local_tools/nb_distribution/run_ssake.pl line 34.
Can't exec "SSAKE": No such file or directory at /mnt/local_tools/nb_distribution/run_ssake.pl line 34.
No such file or directory at /mnt/local_tools/nb_distribution/run_ssake.pl line 39.
Can't exec "SSAKE": No such file or directory at /mnt/local_tools/nb_distribution/run_ssake.pl line 34.
No such file or directory at /mnt/local_tools/nb_distribution/run_ssake.pl line 39.
No such file or directory at /mnt/local_tools/nb_distribution/run_ssake.pl line 39.
Can't exec "SSAKE": No such file or directory at /mnt/local_tools/nb_distribution/run_ssake.pl line 34.
No such file or directory at /mnt/local_tools/nb_distribution/run_ssake.pl line 39.
[E::bwa_idx_load] fail to locate the index files
x??
No such file or directory at /mnt/local_tools/nb_distribution/infer_bp_v4.pl line 13.

Any ideas?

Thanks

**Comment by czc** [comment]
All I can guess is the PATH setting on your system. 
What was your command line?
What will be shown on your terminal after you have exported the PATH and type SSAKE?
Can you try to map a small fastq file using bwa and your indexed reference?

**Comment by d-kk** [comment]
You are correct, the path was set wrong, user error :(

Would you be able to send me a .pdf of the novoBreak paper? I saw this presented at ISMB a couple of years ago, but would love to read the paper...

Thanks for the help!

**Comment by czc** [comment]
Good to know! You are welcome. The paper is available at https://www.nature.com/articles/nmeth.4084

**Comment by GangyuSun** [comment]
> It's not the error of infer_bp_v4.pl. You should index your reference using bwa. Also, make sure the novoBreak directory is in your PATH. Thanks!
> 
> -Zechen

I also have this problem. Is it only use bwa to index my reference can make it work correctly?  I used the samtools to index my reference
