### ISSUE TITLE
fail to locate the index file

### ISSUE THREAD

**Issue by GangyuSun** [czc/nb_distribution#6]
I have tried all my ways to run novoBreak, but this error always occurred,`[E::bwa_idx_load] fail to locate the index files`. Just as some closed issues. 
I'm sure I have indexed my reference by bwa, and even put all the input files in the software folder. It still doesn't work. I wander to know if there some rules in the naming of input files? especially the index files.
All errors output as follows : 
```
Program exit normally
[M::bam2fq_mainloop] processed 9822 reads
begin kmer2id ...
kmer2id takes 0 seconds
begin id2pair...
id2pair takes 1 seconds
begin sorting ids...
sorting ids takes 0 seconds
begin output results...
Outputting results takes 1 seconds
Finished
[E::bwa_idx_load] fail to locate the index files
No such file or directory at /public/home/zhangjing1/software/novoBreak/nb_distribution/infer_bp_v4.pl line 13.
```

**Comment by ShixiangWang** [comment]
@SunssAria Our problem has been fixed, you can close it now.
