### ISSUE TITLE
cant find bwa index

### ISSUE THREAD

**Issue by QinZhen1995** [czc/nb_distribution#8]
HI !  
I pretty sure I made a reference by BWA , and its directory is same as my reference fasta file ,  and the only different between index name with my reference name is its postfix,which one is .fa another  is  bwt and amb....
I also pretty sure my environment is very very  right ,I can type SSMAKE and type enter get right content 
And i install this through git clone 2 days ago , mybe it can prove it is not version problem 
 
THANKS for you job but its really hard for me to deal with this bug 

``` [E::bwa_idx_load] fail to locate the index files
x??
```

**Comment by QinZhen1995** [comment]
log erroor `
`` [E::bwa_idx_load] fail to locate the index files```
my command line
```
#!/bin/bash
echo "["`date +%Y-%m-%d,%H:%M:%S`"] Start novobreak"
nohup run_novoBreak.sh /data/user/XXX/software/nb_distribution/ \
    ~/XXX/XXX.fa \
    ~/XXXanaliysi/finalbams/XXXX.bam \
    ~/XXXanaliysi/finalbams/XXXX.bam 25 
echo "["`date +%Y-%m-%d,%H:%M:%S`"] finish "
```

**Comment by ShixiangWang** [comment]
You need set the directory for novoBreak as working directory.

Add the following code before you run novobreak.

```
cd `which run_novoBreak.sh`
```

**Comment by QinZhen1995** [comment]
> You need set the directory for novoBreak as working directory.
> 
> Add the following code before you run novobreak.
> 
> ```
> cd `which run_novoBreak.sh`
> ```

Thanks 
But it seems not work,First  you can't cd a file,and then by reading source I notice the <ref> para only need the prefix of the fasta file . I think  i found the reason of this problem ,and i hope a more specifically manual of this software will be push .
